server:
  port: 9090
gcp:
  storage:
    enabled: false
    bucket:
      name: migangqui-sample
    keyfile: "where-you-keyfile"
aws:
  s3:
    enabled: true
    accessKey: foobar
    secretKey: foobar
    bucket.name: mytestbucket
  region: us-east-1

azure:
  blob:
    storage:
      enabled: false
      connectionString: "yourconnectionstring"
      container:
        name: images
localstack:
  enabled: true
  endpoint: http://localhost:4572
  region: us-east-1