server:
  port: 9090
gcp:
  storage:
    enabled: true
    bucket:
      name: migangqui-sample
    keyfile: "where-you-keyfile"
aws:
  s3:
    enabled: true
    accessKey: foobar
    secretKey: foobar
    bucket.name: mytestbucket
  region: us-east-1
localstack:
  enabled: true
  endpoint: http://localhost:4572
  region: us-east-1